[package]
name = "runtime-vis"
version = "0.1.0"
authors = ["Alexander Vo <randomcivvy0121@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dot = "0.1.4"
glob = "0.3.0"
